### ISSUE TITLE
Apply class to svg itself

### ISSUE THREAD

**Issue by czeckd** [czeckd/angular-svg-icon#93]
Hi @czeckd, its a really neat plugin!

About the applyCss, it only work if the applied class is specific for using with the svg element. In my case, i have class that's for general use, for example:

```css
.h-12 {
    height: 3rem;
}
```

If i use the applyCss like this:

```html
<svg-icon [applyCss]="true" class="h-12" src="assets/images/test.svg"></svg-icon>
```

It won't work, because my class don't apply the styles to the <svg> element. Is there any way to make the class applied to the ```<svg-icon>``` be transported to the ```<svg>``` tag?

_Originally posted by @filipedtristao in https://github.com/czeckd/angular-svg-icon/issues/58#issuecomment-588521108_

**Comment by czeckd** [comment]
@filipedtristao 

To work like you suggest, it will need some code change. For now, you can work around the issue by adding this to your scss:

```scss
.h-12 {
    height: 3rem;

    svg {
        height: 3rem;
    }
}
```

**Comment by czeckd** [comment]
@filipedtristao - This should work with angular-svg-icon@9.1.0 now.

**Comment by MaximSagan** [comment]
@czeckd 
This commit broke the SVGs in our app. With this commit, it makes it near impossible to apply classes to the `<svg-icon>` host element itself.
If the `applyCss` input is `false` (or not specified), the class will on the host element will be removed (unclear why).
If the `applyCss` is `true`, the class on the host element will be duplicated onto the svg element (again, I don't understand why anybody would desire this behavior).

**Comment by czeckd** [comment]
@MaximSagan Please open a new issue with a small example to reproduce your use case. Thanks.

**Comment by filipedtristao** [comment]
> If the `applyCss` is `true`, the class on the host element will be duplicated onto the svg element (again, I don't understand why anybody would desire this behavior).

@MaximSagan we use tailwindcss in our application, so usually we don't have specific classes for ours SVG elements, instead of that, we use generic classes to stylize. 

Like this:

```html
<svg-icon ... class='fill-current text-red-500 h-8 w-8'></svg-icon>
```

And the CSS for this classes is like this:

```css

.fill-current {
  fill: currentColor;
}

.text-red-500 {
  color: #f56565;
}

.h-8 {
  height: 2rem;
}

.w-8 {
  width: 2rem;
}

```

In this case, if the classes are applied to ```<svg-icon>``` and not to the ```svg``` element, it won't work.

**Comment by MaximSagan** [comment]
> In this case, if the classes are applied to `<svg-icon>` and not to the `svg` element, it won't work.

I understand why you'd want a class on the `svg` element (as opposed to its parent, the `<svg-icon>` component host element), but I'm questioning why you'd want to apply the same class on both elements at the same time.

**Comment by filipedtristao** [comment]
> I understand why you'd want a class on the `svg` element (as opposed to its parent, the `<svg-icon>` component host element), but I'm questioning why you'd want to apply the same class on both elements at the same time.

I don't want the classes to be applied to both at the same time. If it only applies to ```<svg>``` it would be fine.

**Comment by czeckd** [comment]
@MaximSagan Please provide an example of how it has broken for you. Ideally the example would have the class / styling you need on the `svg-icon` component instead of the `svg`.

**Comment by vaindil** [comment]
This is a pretty significant change to not be mentioned anywhere other than this issue. It has broken a ton of our CSS rules that expect the class to be applied only to the `<svg-icon>` element itself, since they're now also being set on the `<svg>` element. Not saying it needs to be reverted, but it should at least be mentioned somewhere in the readme or a changelog.

**EDIT:** A specific CSS rule that was broken is below. It expects that the `checked` class only applies to the top-level `svg-icon` element, but now the svg itself is hidden because it has the `checked` class and isn't a sibling of the checked radio button.

```less
// hidden by default
input[type="radio"],
.checked {
  display: none;
}

// display if a sibling of the checked radio button
input[type="radio"]:checked ~ .checked {
  display: inline-block;
}
```
